/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_fuzzer_sharedmemory_Shm */

#ifndef _Included_com_example_fuzzer_sharedmemory_Shm
#define _Included_com_example_fuzzer_sharedmemory_Shm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_fuzzer_sharedmemory_Shm
 * Method:    createSharedMemory
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_fuzzer_sharedmemory_Shm_createSharedMemory
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_fuzzer_sharedmemory_Shm
 * Method:    readSharedMemory
 * Signature: (II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_fuzzer_sharedmemory_Shm_readSharedMemory
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_fuzzer_sharedmemory_Shm
 * Method:    destroySharedMemory
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_fuzzer_sharedmemory_Shm_destroySharedMemory
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
